### ISSUE TITLE
ValidationError: The requested DurationSeconds exceeds the MaxSessionDuration set for this role

### ISSUE THREAD

**Issue by alexthewilde** [kreuzwerker/awsu#27]
Release [2.2.0](https://github.com/kreuzwerker/awsu/releases/tag/2.2.0)

```
[kreuzwerker]
aws_access_key_id=XXX
aws_secret_access_key=XXX
mfa_serial=arn:aws:iam::113030XXXXXX:mfa/alex.wilde@kreuzwerker.de
region=eu-central-1

[seachefs]
role_arn=arn:aws:iam::976760XXXXXX:role/xw-operator-cross-account
source_profile=kreuzwerker
mfa_serial=arn:aws:iam:: 113030XXXXXX:mfa/alex.wilde@kreuzwerker.de
```

`$ awsu -p seachefs -s 900s -v -n -- aws s3 ls`

Error: failed to aquire credentials for profile "seachefs": failed to assume role "arn:aws:iam::[IAMID]:role/xw-operator-cross-account": ValidationError: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.
	status code: 400, request id: 3ff3d68f-6d61-11e8-83f8-014ef402c6d5

**Comment by brotbert** [comment]
Duplicates #26.
