### ISSUE TITLE
Hardcoded account ID in source code?

### ISSUE THREAD

**Issue by forsberg** [kreuzwerker/awsu#35]
Looking at the source code, it looks like there's a hardcoded Amazon account ID (015428540659) as client_id in one of the generated URLs for the `awsu console` command. 

Is is supposed to be like that, or is it an unfortunate copy-paste accident?

https://github.com/kreuzwerker/awsu/blob/fb48af2c5ebd84ab011ca7531333f1b1df0adcbc/console/console.go#L163

**Comment by craighurley** [comment]
That's a magic AWS account ID associated with the AWS signin page.  You can see it by viewing the source on https://aws.amazon.com/marketplace/management/signin

**Comment by yawn** [comment]
Thanks for the keen eye @forsberg and thanks @craighurley for the explanation. We'll add a comment linking to the issue next release.
