### ISSUE TITLE
v2.3.6 is missing a binary

### ISSUE THREAD

**Issue by deploymentking** [kreuzwerker/awsu#59]
## Expected Behavior

* When I uninstall and reinstall via `brew tap kreuzwerker/taps && brew reinstall kreuzwerker/taps/awsu` I expect to get a linked binary in `/usr/local/bin/awsu` but I do not

## Actual Behavior

There is no binary in `/usr/local/bin/awsu` or `/usr/local/Cellar/awsu/2.3.6` and therefore nothing to symlink and therefore the `awsu` command does not work

## Steps to Reproduce (including precondition)

* Install v2.3.6 of `awsu`

## Screenshot on This Problem (if possible)

![awsu](https://user-images.githubusercontent.com/3706672/143846543-4d4dd38d-e2c6-45ec-aa5b-28a512854aac.jpg)

## Your Environment

- OS: macOS Monteray 12.0.1
- passgen version:

**Comment by mavogel** [comment]
![Screenshot 2021-11-30 at 08 03 07](https://user-images.githubusercontent.com/8409778/144001030-2f496807-bc8b-4d51-9d55-84c98f145ecf.png)

True. Let me check....
