### ISSUE TITLE
Assets for amd64 weren't released in the latest version `v2.3.10`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kreuzwerker/awsu#64]
## Expected Behavior

Assets `awsu_2.3.10_Darwin_x86_64.tar.gz` and `awsu_2.3.10_Linux_x86_64.tar.gz` were released in [GitHub Releases](https://github.com/kreuzwerker/awsu/releases/tag/v2.3.10).

## Actual Behavior

Assets for amd64 weren't released in the latest version `v2.3.10`

## Screenshot on This Problem (if possible)

https://github.com/kreuzwerker/awsu/releases/tag/v2.3.10

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/13323303/219025540-dd2e1269-9690-45bb-a5e5-7d13a39a8c1b.png">

On the other hand, assets for amd64 were released in v2.3.9.

https://github.com/kreuzwerker/awsu/releases/tag/v2.3.9

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/13323303/219026177-60e534fb-4fc1-4d1f-ba91-f5cef3484aab.png">

**Comment by suzuki-shunsuke** [comment]
The release workflow succeeded.

https://github.com/kreuzwerker/awsu/actions/runs/4181648712

**Comment by mavogel** [comment]
good catch. Will investigate
